name: build-os
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  merge_group:
  workflow_dispatch:

jobs:
  build:
    name: Download test image
    strategy:
      fail-fast: false
      matrix:
        cache-key:
          - ''
          - base-image-2024-03-15-raspios-bookworm-arm64-lite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and cache RPI OS image
        id: download
        uses: ./
        with:
          url: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-03-15/2024-03-15-raspios-bookworm-arm64-lite.img.xz
          destination: /tmp/downloads-cache/2024-03-15-raspios-bookworm-arm64-lite
          cache-key: ${{ matrix.cache-key }}

      - name: Show the downloaded file
        run: ls -l "${{ steps.download.outputs.destination }}"
